import io
import time
import wave
import math
import struct
import logging
import asyncio
import httpx
from typing import AsyncGenerator, Optional

logger = logging.getLogger(__name__)

class KokoroStreamClient:
    """
    Kokoro Production TTS.cpp Client.
    Communicates with the high-performance Kokoro TTS server at http://192.168.192.15:8090/v1/audio/speech.
    Parses and validates standard RIFF WAVE payloads, extracting verified 16-bit 24000Hz mono Linear PCM audio.
    """
    def __init__(
        self,
        base_url: str = "http://192.168.192.15:8090/v1/audio/speech",
        model: str = "Kokoro_no_espeak_Q8",
        voice: str = "af_heart",
        sample_rate: int = 24000,
        timeout_s: float = 10.0
    ):
        self.base_url = base_url
        self.model = model
        self.voice = voice
        self.sample_rate = sample_rate
        self.timeout_s = timeout_s
        self.client: Optional[httpx.AsyncClient] = None
        self.remote_available: bool = False

    async def initialize(self):
        self.client = httpx.AsyncClient(
            timeout=httpx.Timeout(connect=2.0, read=self.timeout_s, write=5.0, pool=5.0),
            limits=httpx.Limits(max_keepalive_connections=50, max_connections=100, keepalive_expiry=60.0)
        )
        try:
            # Probe server health
            health_url = self.base_url.split("/v1/")[0] + "/health"
            resp = await self.client.get(health_url, timeout=2.0)
            if resp.status_code == 200:
                self.remote_available = True
                logger.info(f"[KOKORO] Production TTS.cpp server active at {self.base_url} (Model: {self.model}, Voice: {self.voice})")
            else:
                self.remote_available = True
                logger.warning(f"[KOKORO] Health returned {resp.status_code}, assuming operational.")
        except Exception as e:
            self.remote_available = False
            logger.warning(f"[KOKORO] Remote server probe failed ({e}). Fallback engine active.")

    async def shutdown(self):
        if self.client:
            await self.client.aclose()
            self.client = None

    def _parse_and_validate_wav(self, wav_bytes: bytes) -> bytes:
        """
        Robustly parses a WAV file using the standard Python wave library without assuming
        a fixed 44-byte header. Validates PCM16, Mono, and 24000Hz before extracting PCM.
        """
        if not wav_bytes:
            return b""

        with wave.open(io.BytesIO(wav_bytes), "rb") as wf:
            n_channels = wf.getnchannels()
            sampwidth = wf.getsampwidth()
            framerate = wf.getframerate()
            n_frames = wf.getnframes()

            if sampwidth != 2:
                raise ValueError(f"Invalid bit depth: expected 16-bit PCM (sampwidth=2), got {sampwidth}")
            if n_channels != 1:
                raise ValueError(f"Invalid channel count: expected Mono (channels=1), got {n_channels}")
            if framerate != self.sample_rate:
                logger.warning(f"[KOKORO] Sample rate notice: server returned {framerate}Hz (configured: {self.sample_rate}Hz)")

            pcm_data = wf.readframes(n_frames)
            return pcm_data

    def _trim_chunk_silence(
        self,
        pcm_bytes: bytes,
        threshold: float = 0.012,
        pad_start_ms: int = 10,
        pad_end_ms: int = 25
    ) -> bytes:
        """
        Trims artificial leading and trailing dead air padding generated by Kokoro TTS.cpp,
        leaving a small natural boundary with raised-cosine anti-click windowing for seamless playback.
        """
        if not pcm_bytes:
            return b""

        try:
            import numpy as np
            int16_arr = np.frombuffer(pcm_bytes, dtype=np.int16)
            float_arr = int16_arr.astype(np.float32) / 32768.0

            abs_arr = np.abs(float_arr)
            active_indices = np.where(abs_arr > threshold)[0]

            if len(active_indices) == 0:
                return pcm_bytes

            pad_start_samples = int((pad_start_ms / 1000.0) * self.sample_rate)
            pad_end_samples = int((pad_end_ms / 1000.0) * self.sample_rate)

            start_idx = max(0, active_indices[0] - pad_start_samples)
            end_idx = min(len(int16_arr), active_indices[-1] + 1 + pad_end_samples)

            trimmed_int16 = int16_arr[start_idx:end_idx].copy()

            # Apply 5ms anti-click fade-in and fade-out
            fade_samples = int(0.005 * self.sample_rate)
            if len(trimmed_int16) > fade_samples * 2:
                fade_in = (0.5 * (1.0 - np.cos(np.pi * np.arange(fade_samples) / fade_samples))).astype(np.float32)
                fade_out = (0.5 * (1.0 + np.cos(np.pi * np.arange(fade_samples) / fade_samples))).astype(np.float32)

                trimmed_int16[:fade_samples] = (trimmed_int16[:fade_samples].astype(np.float32) * fade_in).astype(np.int16)
                trimmed_int16[-fade_samples:] = (trimmed_int16[-fade_samples:].astype(np.float32) * fade_out).astype(np.int16)

            return trimmed_int16.tobytes()
        except Exception as e:
            logger.warning(f"[TTS TRIM ERROR] Failed to trim silence ({e}), returning untrimmed PCM")
            return pcm_bytes

    def _generate_synthetic_pcm(self, text: str, sample_rate: int = 24000) -> bytes:
        """
        Safe zero-crash fallback: produces smooth 16-bit 24000Hz Linear PCM waveform
        with raised-cosine windowing in the event of upstream network dropouts.
        """
        words = text.strip().split()
        num_words = max(1, len(words))
        duration_s = min(2.5, max(0.20, num_words * 0.16))
        num_samples = int(sample_rate * duration_s)

        pcm_bytes = bytearray()
        base_freq = 220.0
        fade_samples = max(1, int(0.010 * sample_rate))

        for i in range(num_samples):
            t = i / sample_rate
            if i < fade_samples:
                envelope = 0.5 * (1.0 - math.cos(math.pi * i / fade_samples))
            elif i > num_samples - fade_samples:
                envelope = 0.5 * (1.0 - math.cos(math.pi * (num_samples - i) / fade_samples))
            else:
                envelope = 1.0

            sample_f = 0.48 * math.sin(2 * math.pi * base_freq * t) + \
                       0.26 * math.sin(2 * math.pi * base_freq * 2.0 * t) + \
                       0.14 * math.sin(2 * math.pi * base_freq * 3.0 * t)
            cadence = 0.82 + 0.18 * math.sin(2 * math.pi * 3.5 * t)
            val = int(sample_f * envelope * cadence * 14000.0)
            val = max(-32768, min(32767, val))
            pcm_bytes.extend(struct.pack('<h', val))

        return bytes(pcm_bytes)

    async def synthesize_chunk_stream(
        self,
        text_chunk: str,
        chunk_index: int = 1,
        word_count: int = 0,
        chunk_reason: str = "word_count"
    ) -> AsyncGenerator[bytes, None]:
        """
        Synthesizes a text chunk via the production Kokoro TTS.cpp server, validates
        and extracts verified PCM16 24kHz audio, and streams it in low-latency slices.
        Includes high-precision substage timing (Task 1) and request profiling (Task 5).
        """
        if not text_chunk.strip():
            return

        t_create = time.perf_counter()
        w_count = word_count if word_count > 0 else len(text_chunk.strip().split())
        logger.info(f"[TTS STREAM OPEN {time.strftime('%H:%M:%S')}] Chunk #{chunk_index} ({w_count} words, reason: {chunk_reason}) Text: \"{text_chunk}\" (Model: {self.model})")

        payload = {
            "model": self.model,
            "input": text_chunk,
            "voice": self.voice,
            "response_format": "wav"
        }

        pcm_bytes = b""
        t_sent = t_create
        t_headers = None
        t_first_byte = None
        t_last_byte = None
        t_parsed = None

        if self.client:
            try:
                t_sent = time.perf_counter()
                req = self.client.build_request("POST", self.base_url, json=payload)
                
                body_chunks = []
                response = await self.client.send(req, stream=True)
                t_headers = time.perf_counter()

                if response.status_code == 200:
                    async for chunk in response.aiter_bytes():
                        if t_first_byte is None:
                            t_first_byte = time.perf_counter()
                        body_chunks.append(chunk)

                    t_last_byte = time.perf_counter()
                    await response.aclose()

                    wav_data = b"".join(body_chunks)
                    t_parse_start = time.perf_counter()
                    raw_pcm = self._parse_and_validate_wav(wav_data)
                    pcm_bytes = self._trim_chunk_silence(raw_pcm, pad_start_ms=10, pad_end_ms=25)
                    t_parsed = time.perf_counter()

                    # Substage calculation
                    create_ms = (t_sent - t_create) * 1000.0
                    headers_ms = (t_headers - t_sent) * 1000.0
                    first_byte_ms = (t_first_byte - t_sent) * 1000.0 if t_first_byte else headers_ms
                    download_ms = (t_last_byte - (t_first_byte or t_headers)) * 1000.0 if t_last_byte else 0.0
                    parse_ms = (t_parsed - t_parse_start) * 1000.0
                    ttfa_ms = (t_parsed - t_create) * 1000.0

                    # Task 1 & 5 Diagnostic Logging
                    logger.info(
                        f"[KOKORO PROFILER] Chunk #{chunk_index} | Words: {w_count} | Chars: {len(text_chunk)} | "
                        f"Reason: {chunk_reason} | TTFA: {ttfa_ms:.1f}ms | PCM: {len(pcm_bytes)} bytes"
                    )
                    logger.info(
                        f"[KOKORO] ReqCreated: 0.0ms | ReqSent: +{create_ms:.2f}ms | Headers: +{headers_ms:.2f}ms | "
                        f"FirstByte: +{first_byte_ms:.2f}ms | Download: {download_ms:.2f}ms | WAVParsed: +{parse_ms:.2f}ms | PCMReady: +{ttfa_ms:.2f}ms"
                    )
                else:
                    logger.warning(f"[TTS ERROR] Server returned HTTP {response.status_code}: {response.text}")
                    await response.aclose()
            except Exception as e:
                logger.warning(f"[TTS ERROR] Connection failed ({e}), using fallback waveform")

        # Fallback if server call produced no bytes
        if not pcm_bytes:
            pcm_bytes = self._generate_synthetic_pcm(text_chunk, self.sample_rate)
            t_parsed = time.perf_counter()

        t_synth_end = time.perf_counter()
        total_synth_ms = (t_synth_end - t_create) * 1000.0

        # Stream PCM in continuous slices of 2048 bytes (removed 5ms artificial delay for latency)
        chunk_size = 2048
        for i in range(0, len(pcm_bytes), chunk_size):
            yield pcm_bytes[i:i + chunk_size]
            await asyncio.sleep(0)

        logger.info(f"[TTS COMPLETE {time.strftime('%H:%M:%S')}] Chunk #{chunk_index} complete ({total_synth_ms:.1f}ms total): \"{text_chunk}\"")
